### ISSUE TITLE
Set password requeired by openssl script

### ISSUE THREAD

**Issue by robrezendeolivia** [codevibess/openssl-nodejs#3]
I tried to run the following script

openssl(`openssl genrsa -des3 -out private.pem 2048`), which requires a passphrase, but I can't send it. Can you provide an array of inputs parameter for cases like this?

**Comment by codevibess** [comment]
Hi, friend
Its no need to add array with input params, you can handle it by openssl one-line command.
Sample:
`openssl(openssl genrsa -des3 -passout pass:foobar -out privkey.pem 2048)`

Output:
`Generating RSA private key, 2048 bit long modulus
..............................+++
.......+++
e is 65537 (0x10001)`

If u have more question, just ask 
If your problem is solved, please close the issue

Regards, 
AC
